import React, { useEffect, useState } from "react";
import { 
  Users, Search, PlusCircle, Edit2, Trash2, 
  AlertCircle, ShieldCheck, X, RefreshCw, UserCheck 
} from "lucide-react";
import { Customer } from "../types";

interface CustomersProps {
  userRole: string;
}

export default function Customers({ userRole }: CustomersProps) {
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Modal forms states
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingCustomer, setEditingCustomer] = useState<Customer | null>(null);
  const [formData, setFormData] = useState({
    id: "",
    name: "",
    type: "ขายปลีก",
    priceGroup: "C" as "A" | "B" | "C",
    paymentTerm: "เงินสด",
    address: "",
    phone: "",
    email: "",
    status: "ใช้งาน" as "ใช้งาน" | "ระงับ"
  });

  // Toast notifications
  const [toast, setToast] = useState<{ type: "success" | "error"; msg: string } | null>(null);

  const showToast = (type: "success" | "error", msg: string) => {
    setToast({ type, msg });
    setTimeout(() => setToast(null), 3000);
  };

  const fetchCustomers = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/customers");
      if (!res.ok) throw new Error("ไม่สามารถโหลดข้อมูลลูกค้าได้");
      const data = await res.json();
      setCustomers(data);
      setError(null);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCustomers();
  }, []);

  const handleOpenForm = (cust: Customer | null = null) => {
    if (userRole === "Viewer") {
      showToast("error", "คุณไม่มีสิทธิ์แก้ไขข้อมูล (สิทธิ์ Viewer เท่านั้น)");
      return;
    }
    if (cust) {
      setEditingCustomer(cust);
      setFormData({
        id: cust.id,
        name: cust.name,
        type: cust.type,
        priceGroup: cust.priceGroup,
        paymentTerm: cust.paymentTerm,
        address: cust.address,
        phone: cust.phone,
        email: cust.email,
        status: cust.status
      });
    } else {
      setEditingCustomer(null);
      setFormData({
        id: "", // Auto-generated by backend if empty
        name: "",
        type: "ขายปลีก",
        priceGroup: "C",
        paymentTerm: "เงินสด",
        address: "",
        phone: "",
        email: "",
        status: "ใช้งาน"
      });
    }
    setIsFormOpen(true);
  };

  const handleSaveCustomer = async (e: React.FormEvent) => {
    e.preventDefault();
    if (userRole === "Viewer") return;

    if (!formData.name) {
      showToast("error", "กรุณากรอกชื่อลูกค้า");
      return;
    }

    try {
      const url = editingCustomer 
        ? `/api/customers/${editingCustomer.id}` 
        : "/api/customers";
      const method = editingCustomer ? "PUT" : "POST";

      const res = await fetch(url, {
        method,
        headers: {
          "Content-Type": "application/json",
          "x-user": "admin"
        },
        body: JSON.stringify(formData)
      });

      const resJson = await res.json();
      if (!res.ok) throw new Error(resJson.message || "เกิดข้อผิดพลาดในการบันทึก");

      showToast("success", editingCustomer ? "แก้ไขข้อมูลลูกค้าสำเร็จ!" : "เพิ่มลูกค้าใหม่สำเร็จ!");
      setIsFormOpen(false);
      fetchCustomers();
    } catch (err: any) {
      showToast("error", err.message);
    }
  };

  const handleDeleteCustomer = async (id: string, name: string) => {
    if (userRole === "Viewer") {
      showToast("error", "คุณไม่มีสิทธิ์ลบข้อมูล");
      return;
    }

    const confirmDelete = window.confirm(`คุณแน่ใจหรือไม่ว่าต้องการลบลูกค้า "${name}"?`);
    if (!confirmDelete) return;

    try {
      const res = await fetch(`/api/customers/${id}`, {
        method: "DELETE",
        headers: {
          "x-user": "admin"
        }
      });

      if (!res.ok) {
        const json = await res.json();
        throw new Error(json.message || "ไม่สามารถลบได้");
      }

      showToast("success", "ลบข้อมูลลูกค้าเรียบร้อยแล้ว");
      fetchCustomers();
    } catch (err: any) {
      showToast("error", err.message);
    }
  };

  const filteredCustomers = customers.filter(c => 
    c.name.toLowerCase().includes(search.toLowerCase()) || 
    c.id.toLowerCase().includes(search.toLowerCase()) || 
    (c.phone && c.phone.includes(search))
  );

  return (
    <div className="space-y-6">
      {/* Toast Alert */}
      {toast && (
        <div className={`fixed top-4 right-4 z-50 p-4 rounded-xl shadow-lg border text-xs font-sans font-semibold flex items-center gap-2 transition-all animate-bounce ${
          toast.type === "success" 
            ? "bg-emerald-50 text-emerald-800 border-emerald-200" 
            : "bg-rose-50 text-rose-800 border-rose-200"
        }`}>
          <AlertCircle className={`w-4 h-4 ${toast.type === "success" ? "text-emerald-600" : "text-rose-600"}`} />
          {toast.msg}
        </div>
      )}

      {/* Header Panel */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 id="customers-title" className="text-2xl font-semibold tracking-tight text-gray-900 font-sans">จัดการข้อมูลลูกค้า (Customers)</h1>
          <p className="text-xs text-gray-500 font-sans mt-0.5">บันทึกรายชื่อลูกค้า กลุ่มราคา และที่อยู่เพื่อความรวดเร็วในการออกใบกำกับบิล</p>
        </div>
        {userRole !== "Viewer" && (
          <button 
            id="add-customer-btn"
            onClick={() => handleOpenForm(null)}
            className="inline-flex items-center gap-2 px-4 py-2 text-xs bg-emerald-600 hover:bg-emerald-700 text-white font-sans font-semibold rounded-lg shadow-sm cursor-pointer transition-colors"
          >
            <PlusCircle className="w-4 h-4" />
            เพิ่มลูกค้าใหม่
          </button>
        )}
      </div>

      {/* Filters and Controls */}
      <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-xs flex flex-col sm:flex-row gap-3 items-center">
        <div className="relative w-full sm:max-w-md">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400" />
          <input 
            type="text" 
            placeholder="ค้นหาตามชื่อลูกค้า, รหัสลูกค้า หรือเบอร์โทรศัพท์..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-9 pr-4 py-2 border border-gray-200 rounded-lg text-xs font-sans focus:outline-hidden focus:ring-1 focus:ring-emerald-500 bg-gray-50/50"
          />
        </div>
        <div className="text-xs font-sans text-gray-400 font-medium ml-auto">
          แสดงทั้งหมด {filteredCustomers.length} ราย
        </div>
      </div>

      {/* Customers Table */}
      <div className="bg-white border border-gray-100 rounded-xl shadow-xs overflow-hidden">
        {loading ? (
          <div className="flex flex-col items-center justify-center p-12 gap-2">
            <RefreshCw className="w-8 h-8 text-emerald-600 animate-spin" />
            <p className="text-xs text-gray-400 font-sans">กำลังดาวน์โหลดข้อมูลลูกค้า...</p>
          </div>
        ) : error ? (
          <div className="p-8 text-center text-rose-600 font-sans text-xs">{error}</div>
        ) : filteredCustomers.length === 0 ? (
          <div className="p-12 text-center text-gray-400 font-sans text-xs">ไม่พบข้อมูลลูกค้าที่ค้นหา</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-gray-50 border-b border-gray-100 text-gray-500 font-sans text-[10px] font-bold uppercase tracking-wider">
                  <th className="py-3.5 px-4">รหัสลูกค้า</th>
                  <th className="py-3.5 px-4">ชื่อ - นามสกุล</th>
                  <th className="py-3.5 px-4">ประเภทกลุ่มค้า</th>
                  <th className="py-3.5 px-4 text-center">กลุ่มราคาสินค้า</th>
                  <th className="py-3.5 px-4">เครดิต / การชำระ</th>
                  <th className="py-3.5 px-4">เบอร์โทรศัพท์ / อีเมล</th>
                  <th className="py-3.5 px-4 text-center">สถานะ</th>
                  {userRole !== "Viewer" && <th className="py-3.5 px-4 text-center">การจัดการ</th>}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 font-sans text-xs text-gray-700">
                {filteredCustomers.map((c) => (
                  <tr key={c.id} className="hover:bg-gray-50/70 transition-colors">
                    <td className="py-4 px-4 font-mono text-xs font-bold text-slate-900">{c.id}</td>
                    <td className="py-4 px-4 font-semibold text-gray-800">
                      {c.name}
                      <span className="block font-normal text-[10px] text-gray-400 mt-1 max-w-xs truncate" title={c.address}>
                        {c.address || "ไม่มีข้อมูลที่อยู่"}
                      </span>
                    </td>
                    <td className="py-4 px-4">
                      <span className={`px-2 py-0.5 rounded-md text-[10px] font-medium ${
                        c.type === "ขายส่ง" ? "bg-purple-50 text-purple-700 border border-purple-100" :
                        c.type === "ตัวแทน" ? "bg-blue-50 text-blue-700 border border-blue-100" :
                        "bg-gray-100 text-gray-700 border border-gray-200"
                      }`}>
                        {c.type}
                      </span>
                    </td>
                    <td className="py-4 px-4 text-center font-bold">
                      <span className={`w-6 h-6 inline-flex items-center justify-center rounded-full border text-xs ${
                        c.priceGroup === "A" ? "bg-indigo-50 border-indigo-200 text-indigo-700" :
                        c.priceGroup === "B" ? "bg-amber-50 border-amber-200 text-amber-700" :
                        "bg-emerald-50 border-emerald-200 text-emerald-700"
                      }`}>
                        {c.priceGroup}
                      </span>
                    </td>
                    <td className="py-4 px-4 font-medium text-gray-600">{c.paymentTerm}</td>
                    <td className="py-4 px-4">
                      <div className="font-mono text-gray-800">{c.phone || "-"}</div>
                      <div className="text-[10px] text-gray-400 mt-0.5">{c.email || "-"}</div>
                    </td>
                    <td className="py-4 px-4 text-center">
                      <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold ${
                        c.status === "ใช้งาน" 
                          ? "bg-emerald-50 text-emerald-700 border border-emerald-200" 
                          : "bg-gray-100 text-gray-500 border border-gray-200"
                      }`}>
                        <ShieldCheck className="w-3 h-3" />
                        {c.status}
                      </span>
                    </td>
                    {userRole !== "Viewer" && (
                      <td className="py-4 px-4 text-center">
                        <div className="inline-flex items-center gap-2">
                          <button 
                            onClick={() => handleOpenForm(c)}
                            className="p-1.5 text-gray-500 hover:text-emerald-600 hover:bg-emerald-50 rounded-lg transition-colors cursor-pointer"
                            title="แก้ไขลูกค้า"
                          >
                            <Edit2 className="w-3.5 h-3.5" />
                          </button>
                          <button 
                            onClick={() => handleDeleteCustomer(c.id, c.name)}
                            className="p-1.5 text-gray-500 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-colors cursor-pointer"
                            title="ลบลูกค้า"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </td>
                    )}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Add / Edit Form Modal */}
      {isFormOpen && (
        <div className="fixed inset-0 z-40 flex items-center justify-center bg-black/50 backdrop-blur-xs p-4">
          <div className="bg-white rounded-2xl border border-gray-100 shadow-xl w-full max-w-lg max-h-[90vh] overflow-y-auto flex flex-col animate-in fade-in zoom-in-95 duration-150">
            <div className="bg-slate-900 text-white px-6 py-4 flex items-center justify-between sticky top-0 z-10">
              <h3 className="font-semibold text-sm font-sans flex items-center gap-2">
                <UserCheck className="w-4 h-4 text-emerald-500" />
                {editingCustomer ? "แก้ไขข้อมูลลูกค้า" : "เพิ่มลูกค้าใหม่ในระบบ"}
              </h3>
              <button 
                onClick={() => setIsFormOpen(false)}
                className="p-1 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={handleSaveCustomer} className="p-6 space-y-4 flex-1">
              <div className="grid grid-cols-2 gap-4">
                {/* ID (Read only if editing) */}
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 font-sans uppercase">รหัสลูกค้า</label>
                  <input 
                    type="text" 
                    disabled
                    value={formData.id || "(ระบบจะสร้างให้อัตโนมัติ)"}
                    className="w-full px-3 py-2 text-xs font-mono border border-gray-200 rounded-lg bg-gray-100 text-gray-400"
                  />
                </div>

                {/* Name */}
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 font-sans uppercase">ชื่อ-นามสกุล หรือชื่อร้านค้า *</label>
                  <input 
                    type="text" 
                    required
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    className="w-full px-3 py-2 text-xs font-sans border border-gray-200 rounded-lg focus:outline-hidden focus:ring-1 focus:ring-emerald-500 bg-gray-50/50"
                    placeholder="เช่น ร้านข้าวแกงป้าแดง"
                  />
                </div>
              </div>

              <div className="grid grid-cols-3 gap-4">
                {/* Type */}
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 font-sans uppercase">ประเภทลูกค้า</label>
                  <select 
                    value={formData.type}
                    onChange={(e) => setFormData({ ...formData, type: e.target.value })}
                    className="w-full px-3 py-2 text-xs font-sans border border-gray-200 rounded-lg focus:outline-hidden focus:ring-1 focus:ring-emerald-500 bg-gray-50/50"
                  >
                    <option value="ขายปลีก">ขายปลีก</option>
                    <option value="ขายส่ง">ขายส่ง</option>
                    <option value="ตัวแทน">ตัวแทน</option>
                  </select>
                </div>

                {/* Price Group */}
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 font-sans uppercase">กลุ่มราคาที่กำหนด</label>
                  <select 
                    value={formData.priceGroup}
                    onChange={(e) => setFormData({ ...formData, priceGroup: e.target.value as "A" | "B" | "C" })}
                    className="w-full px-3 py-2 text-xs font-sans border border-gray-200 rounded-lg focus:outline-hidden focus:ring-1 focus:ring-emerald-500 bg-gray-50/50 font-bold text-emerald-700"
                  >
                    <option value="A">กลุ่มราคา A (ราคาส่งต่ำสุด)</option>
                    <option value="B">กลุ่มราคา B (ราคาตัวแทน)</option>
                    <option value="C">กลุ่มราคา C (ราคาปลีกมาตรฐาน)</option>
                  </select>
                </div>

                {/* Payment Term */}
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 font-sans uppercase">การชำระเงิน</label>
                  <select 
                    value={formData.paymentTerm}
                    onChange={(e) => setFormData({ ...formData, paymentTerm: e.target.value })}
                    className="w-full px-3 py-2 text-xs font-sans border border-gray-200 rounded-lg focus:outline-hidden focus:ring-1 focus:ring-emerald-500 bg-gray-50/50"
                  >
                    <option value="เงินสด">เงินสด</option>
                    <option value="เครดิต 15 วัน">เครดิต 15 วัน</option>
                    <option value="เครดิต 30 วัน">เครดิต 30 วัน</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                {/* Phone */}
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 font-sans uppercase">เบอร์โทรศัพท์</label>
                  <input 
                    type="text" 
                    value={formData.phone}
                    onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                    className="w-full px-3 py-2 text-xs font-mono border border-gray-200 rounded-lg focus:outline-hidden focus:ring-1 focus:ring-emerald-500 bg-gray-50/50"
                    placeholder="081-XXXX-XXX"
                  />
                </div>

                {/* Email */}
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 font-sans uppercase">อีเมล (Email)</label>
                  <input 
                    type="email" 
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    className="w-full px-3 py-2 text-xs font-sans border border-gray-200 rounded-lg focus:outline-hidden focus:ring-1 focus:ring-emerald-500 bg-gray-50/50"
                    placeholder="customer@example.com"
                  />
                </div>
              </div>

              {/* Address */}
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-gray-500 font-sans uppercase">ที่อยู่จัดส่งและออกบิล</label>
                <textarea 
                  rows={2}
                  value={formData.address}
                  onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                  className="w-full px-3 py-2 text-xs font-sans border border-gray-200 rounded-lg focus:outline-hidden focus:ring-1 focus:ring-emerald-500 bg-gray-50/50 resize-none"
                  placeholder="หมู่บ้าน ซอย ถนน ตำบล อำเภอ จังหวัด..."
                />
              </div>

              {/* Status */}
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-gray-500 font-sans uppercase">สถานะบัญชี</label>
                <select 
                  value={formData.status}
                  onChange={(e) => setFormData({ ...formData, status: e.target.value as "ใช้งาน" | "ระงับ" })}
                  className="w-full px-3 py-2 text-xs font-sans border border-gray-200 rounded-lg focus:outline-hidden focus:ring-1 focus:ring-emerald-500 bg-gray-50/50"
                >
                  <option value="ใช้งาน">ใช้งาน</option>
                  <option value="ระงับ">ระงับ</option>
                </select>
              </div>

              <div className="flex items-center justify-end gap-3 pt-4 border-t border-gray-100">
                <button 
                  type="button"
                  onClick={() => setIsFormOpen(false)}
                  className="px-4 py-2 text-xs font-semibold text-gray-500 hover:text-gray-700 font-sans cursor-pointer"
                >
                  ยกเลิก
                </button>
                <button 
                  type="submit"
                  className="px-4 py-2 text-xs font-semibold text-white bg-emerald-600 hover:bg-emerald-700 rounded-lg shadow-sm font-sans cursor-pointer"
                >
                  {editingCustomer ? "บันทึกการแก้ไข" : "บันทึกข้อมูลลูกค้า"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
